runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: src.main.app
# report allow staff to view their planning
- url: /report/.*
  script: src.main.app
- url: /report-list
  script: src.main.app
  login: admin
# API exposes data to frontends
- url: /api.*
  script: src.main.app
# Changelist blueprint that deals with pending and recent changes
- url: /changelist.*
  script: src.main.app
  login: admin
# Caldav blueprint handles iCal Synchronization
- url: /calsync.*
  script: src.main.app
  login: admin
# Refresh regenerates the calendar, used by cron job
- url: /refresh
  script: src.main.app
  login: admin
# admin frontend
- url: /admin
  script: src.main.app
  login: admin
# static files
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon\.ico

libraries:
- name: lxml
  version: latest
- name: ssl
  version: latest
