application: ecal-planneur
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: src.main.app
- url: /detail/.*
  script: src.main.app
- url: /admin
  script: src.main.app
- url: /api/.*
  script: src.main.app
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: www/res/favicon.ico
  upload: www/res/favicon\.ico

libraries:
