application: ecal-planneur
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: src.main.app
- url: /detail/.*
  script: src.main.app
- url: /report/.*
  script: src.main.app
- url: /changelist
  script: src.main.app
- url: /changelist/.*
  script: src.main.app
- url: /report_staff_changelist/.*
  script: src.main.app
- url: /silence_staff_changelist/.*
  script: src.main.app
- url: /admin
  script: src.main.app
  login: admin
- url: /api/.*
  script: src.main.app
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon\.ico

libraries:
