start: 2 # 1st of August 2018 is a Wednesday

days:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
  - Saturday
  - Sunday

months:
  - label: August
    days: 31
  - label: September
    days: 30
  - label: October
    days: 31
  - label: November
    days: 30
  - label: December
    days: 31
  - label: January
    days: 31
  - label: February
    days: 28
  - label: March
    days: 31
  - label: April
    days: 30
  - label: May
    days: 31
  - label: June
    days: 30
  - label: July
    days: 31

special:
  nocourse:
    - label: prepare 18-19
      start: 20/08
      end: 24/08
    - label: prepare 18-19
      start: 27/08
      end: 31/08
    - label: helper courses
      start: 03/09
      end: 07/09
    - label: helper courses
      start: 10/09
      end: 14/09
    - label: projects week
      start: 11/02
      end: 15/02
    - label: remediations
      start: 28/01
      end: 1/02
    - label: remediations
      start: 4/02
      end: 8/02
    - label: remediations
      start: 24/06
      end: 28/07
    - label: remediations
      start: 1/07
      end: 5/07
  holiday:
    - label: summer
      start: 01/08
      end: 17/08
    - label: jeune federal
      start: 17/09
      end: 17/09
    - label: autumn break
      start: 22/10
      end: 26/10
    - label: christmas
      start: 24/12
      end: 4/01
    - label: winter break
      start: 25/02
      end: 01/03
    - label: saint friday
      start: 30/03
      end: 30/03
    - label: easter
      start: 2/04
      end: 6/04
    - label: ascension
      start: 19/04
      end: 19/04
    - label: pentecote
      start: 22/04
      end: 26/04
    - label: summer
      start: 15/07
      end: 31/07
  workshop:
    - label: block week s1
      start: 1/10
      end: 5/10
    - label: block week s1
      start: 29/10
      end: 2/11
    - label: workshop s1
      start: 12/11
      end: 16/11
    - label: block week s1
      start: 3/12
      end: 7/12
    - label: block week s2
      start: 18/02
      end: 22/02
    - label: block week s2
      start: 25/03
      end: 29/03
    - label: workshop s2
      start: 29/04
      end: 3/05
    - label: block week s2
      start: 13/05
      end: 17/05
  evals:
    - label: evals s1
      start: 14/01
      end: 18/01
    - label: evals m&id
      start: 21/01
      end: 23/01
    - label: evals m&id
      start: 12/06
      end: 14/06
    - label: diplomes
      start: 19/06
      end: 20/06
    - label: diplomes m&id
      start: 21/06
      end: 21/06
