Staffs:

# Profs

- name: Alain Bellet
  role: Professor
  percent: 50
  email: alain.bellet@ecal.ch
  tasks:
    - kind: course
      course: 2cvmid11b
    - kind: course
      course: 2cvmid21b
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: recherche
      hours: 370
      locked: 1

- name: Angelo Benedetto
  role: Professor
  percent: 16
  email: angelo.benedetto@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid11c
    - kind: course
      course: 1cvmid22a
    - kind: course
      course: 1cvmid21c
    - kind: eval

- name: Pauline Saglio
  role: Professor
  percent: 70
  email: pauline.saglio@ecal.ch
  tasks:
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: course
      course: 3cvtrans1
    - kind: resp mid
      hours: 374
    - kind: eval
    - kind: diplome_blanc
    - kind: thesis_reading
      hours: 16
      locked: 1
    - kind: eval_thesis

- name: Christophe Guignard
  role: Professor
  percent: 40
  email: christophe.guignard@ecal.ch
  tasks:
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: course
      course: 3cvmid22
    - kind: 3cvmid_thesis
      coef: 2.2
    - kind: 2cvmid_thesis
      coef: 2.2
    - kind: 1cvmid_theory1
      coef: 2.2
    - kind: pp
      coef: 2.2
      hours: 15
      locked: 1
    - kind: 1cvmid_theory2
      coef: 2.2
      hours: 40
      locked: 1
    - kind: thesis_reading
      hours: 64
      locked: 1e
    - kind: eval_thesis
    - kind: eval_pp
      hours: 16
      locked: 1

- name: Gael Hugo
  role: Professor
  percent: 40
  email: gael.hugo@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid11a
    - kind: course
      course: 1cvmid22b
    - kind: course
      course: 2cvmid11a
    - kind: course
      course: 2cvmid21a
    - kind: course
      course: 3cvmid12
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc

- name: Patrick Keller
  role: Professor
  percent: 50
  email: patrick.keller@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid11b
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: theory1
      coef: 2.2
      hours: 40
      locked: 1
    - kind: theory2
      coef: 2.2
      hours: 40
      locked: 1
    - kind: r&d
      hours: 560
      locked: 1

- name: Vincent Jacquier
  role: Professor
  percent: 100
  email: vincent.jacquier@ecal.ch
  tasks:
    - kind: course
      course: 2cvmid12c
    - kind: course
      course: 3cvtrans1

# Assistants

- name: Tibor Udvari
  role: Assistant
  percent: 50
  email: tibor.udvari@ecal.ch
  tasks:
  - kind: assist
  - kind: intro_course
    coef: 2.2

- name: Pietro Alberti
  role: Assistant
  percent: 40
  email: pietro.alberti@ecal.ch
  tasks:
  - kind: assist
  - kind: intro_course
    coef: 2.2

- name: Laura Perrenoud
  role: Assistant
  percent: 30
  email: laura.perrenoud@ecal.ch
  tasks:
  - kind: assist

- name: Callum Ross
  role: Assistant
  percent: 50
  email: marc.dubois@ecal.ch
  tasks:
  - kind: assist

# Lecturers

- name: Mario VonRickenbach
  role: Lecturer
  hours: 0
  email: mario.vonricke@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid12a
    - kind: course
      course: 1cvmid21b
    - kind: course
      course: 3cvmid2
    - kind: eval

- name: Cedric Duchene
  role: Lecturer
  hours: 40
  email: cedric.duchene@epfl.ch
  tasks:
    - kind: course
      course: 2cvmid22b
    - kind: course
      course: 3cvmid2
    - kind: diplome_blanc

- name: Andreas Gysin
  role: Lecturer
  hours: 80
  email: andreas@ertdfgcvb.com
  tasks:
    - kind: course
      course: 1cvmid12b
    - kind: course
      course: 2cvmid22a

- name: Florian Pittet
  role: Lecturer
  hours: 40
  email: florian@sigma6.ch
  tasks:
    - kind: course
      course: 2cvmid12c

- name: Jürg Lehni
  role: Lecturer
  hours: 80
  email: juerg@lehni.org
  tasks:
    - kind: course
      course: 1cvmid12c
    - kind: course
      course: 2cvmid22b

- name: Cyril Diagne
  role: Lecturer
  hours: 80
  email: diagne.cyril@gmail.com
  tasks:
    - kind: course
      course: 2cvmid12a
    - kind: course
      course: 1cvmid22c
