start: 0 # 1st of August 2016 is a Monday

days:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
  - Saturday
  - Sunday

months:
  - label: August
    days: 31
  - label: September
    days: 30
  - label: October
    days: 31
  - label: November
    days: 30
  - label: December
    days: 31
  - label: January
    days: 31
  - label: February
    days: 28
  - label: March
    days: 31
  - label: April
    days: 30
  - label: May
    days: 31
  - label: June
    days: 30
  - label: July
    days: 31

special:
  nocourse:
    - label: prepare 16-17
      start: 15/08
      end: 09/09
    - label: projects week
      start: 13/02
      end: 17/02
    - label: helper courses
      start: 12/09
      end: 16/09
  holiday:
    - label: summer
      start: 01/08
      end: 12/08
    - label: jeune federal
      start: 19/09
      end: 19/09
    - label: autumn break
      start: 24/10
      end: 28/10
    - label: christmas
      start: 26/12
      end: 06/01
    - label: winter break
      start: 20/02
      end: 24/02
    - label: saint friday
      start: 14/04
      end: 14/04
    - label: easter
      start: 17/04
      end: 21/04
    - label: easter
      start: 25/05
      end: 26/05
    - label: pentecote
      start: 5/06
      end: 5/06
    - label: pentecote
      start: 5/06
      end: 5/06
    - label: summer
      start: 17/07
      end: 31/07
  workshop:
    - label: block week s1
      start: 3/10
      end: 7/10
    - label: block week s1
      start: 31/10
      end: 4/11
    - label: workshop s1
      start: 14/11
      end: 18/11
    - label: block week s1
      start: 5/12
      end: 9/12
    - label: block week s2
      start: 6/03
      end: 10/03
    - label: block week s2
      start: 27/03
      end: 31/03
    - label: workshop s2
      start: 24/04
      end: 28/04
    - label: block week s2
      start: 8/05
      end: 12/05
  evals:
    - label: evals s1
      start: 16/01
      end: 20/01
    - label: evals m&id
      start: 23/01
      end: 25/01
    - label: evals s2
      start: 12/06
      end: 14/06
    - label: evals m&id
      start: 15/06
      end: 16/06
    - label: diplomes
      start: 21/06
      end: 22/06
    - label: diplomes m&id
      start: 23/06
      end: 23/06
