Staffs:

# Profs

- name: Patrick Keller
  role: Professor
  percent: 50
  email: patrick.keller@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid11b
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: theory1
      coef: 2.2
      hours: 40
      locked: 1
    - kind: theory2
      coef: 2.2
      hours: 40
      locked: 1
    - kind: r&d
      hours: 560
      locked: 1

- name: Christophe Guignard
  role: Professor
  percent: 40
  email: christophe.guignard@ecal.ch
  tasks:
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: course
      course: 3cvmid22
    - kind: pp
      coef: 2.2
      hours: 15
      locked: 1
    - kind: theory1
      coef: 2.2
      hours: 40
      locked: 1
    - kind: theory2
      coef: 2.2
      hours: 36
      locked: 1
    - kind: thesis
      coef: 2.2
      hours: 64
      locked: 1
    - kind: thesis_reading
      hours: 48
      locked: 1
    - kind: eval_thesis
    - kind: eval_pp
      hours: 16
      locked: 1

- name: Alain Bellet
  role: Professor
  percent: 50
  email: alain.bellet@ecal.ch
  tasks:
    - kind: course
      course: 2cvmid12a
    - kind: course
      course: 2cvmid12c
    - kind: course
      course: 2cvmid22a
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: when_objects_dream

- name: Angelo Benedetto
  role: Professor
  percent: 16
  email: angelo.benedetto@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid12a
    - kind: course
      course: 1cvmid12b
    - kind: course
      course: 1cvmid22a
    - kind: eval

- name: Gael Hugo
  role: Professor
  percent: 40
  email: gael.hugo@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid21a
    - kind: course
      course: 1cvmid22c
    - kind: course
      course: 2cvmid11a
    - kind: course
      course: 2cvmid21a
    - kind: course
      course: 3cvmid12
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: representation

- name: Cyril Diagne
  role: Professor
  percent: 60
  email: cyril.diagne@ecal.ch
  tasks:
    - kind: course
      course: 1cvmid11a
    - kind: course
      course: 1cvmid12b
    - kind: course
      course: 2cvmid12c
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: course
      course: 3cvtrans1
    - kind: entry_test
      hours: 24
    - kind: resp mid
      hours: 374
    - kind: resp_mid_rdu
    - kind: projects
      hours: 80
    - kind: eval
    - kind: diplome_blanc
    - kind: thesis_reading
      hours: 16
      locked: 1
    - kind: eval_thesis

# Assistants

- name: Tibor Udvari
  role: Assistant
  percent: 50
  email: tibor.udvari@ecal.ch
  tasks:
  - kind: assist
  - kind: intro_course
    coef: 2.2

- name: Laura Perrenoud
  role: Assistant
  percent: 30
  email: laura.perrenoud@ecal.ch
  tasks:
  - kind: assist
  - kind: intro_course
    coef: 2.2

- name: Marc Dubois
  role: Assistant
  percent: 30
  email: marc.dubois@ecal.ch
  tasks:
  - kind: assist
  - kind: assist_web
  - kind: assist_harry
  - kind: assist_trans

- name: Romain Cazier
  role: Assistant
  percent: 60
  email: romain.cazier@ecal.ch
  tasks:
  - kind: assist
  - kind: san_francisco
    hours: 220
    locked: 1

# Lecturers

- name: Cedric Duchene
  role: Lecturer
  hours: 40
  email: cedric.duchene@epfl.ch
  tasks:
    - kind: course
      course: 2cvmid22b
    - kind: course
      course: 3cvmid2
    - kind: diplome_blanc

- name: Andreas Gysin
  role: Lecturer
  hours: 80
  email: andreas@ertdfgcvb.com
  tasks:
    - kind: course
      course: 2cvmid11b
    - kind: course
      course: 1cvmid22c

- name: Mario VonRickenbach
  role: Lecturer
  hours: 136
  email: mario@mariov.ch
  tasks:
    - kind: course
      course: 2cvmid12b
    - kind: course
      course: 1cvmid11c
    - kind: course
      course: 1cvmid21b
    - kind: course
      course: 3cvmid2
    - kind: eval

- name: Florian Pittet
  role: Lecturer
  hours: 40
  email: florian@sigma6.ch
  tasks:
    - kind: course
      course: 1cvmid12c

- name: Jussi Angesleva
  role: Lecturer
  hours: 24
  email: jussi.angesleva@iki.fi
  tasks:
    - kind: course
      course: 3cvmid11
