Staffs:

# Profs

- name: Patrick Keller
  role: Professor
  percent: 50
  tasks:
    - kind: course
      course: 1cvmid11b
    - kind: eval
    - kind: diplome_blanc
    - kind: theory1
      coef: 2.2
      hours: 40
      locked: 1
    - kind: theory2
      coef: 2.2
      hours: 40
      locked: 1
    - kind: r&d
      hours: 560
      locked: 1

- name: Christophe Guignard
  role: Professor
  percent: 40
  tasks:
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: course
      course: 3cvmid22
    - kind: pp
      coef: 2.2
      hours: 24
      locked: 1
    - kind: theory1
      coef: 2.2
      hours: 40
      locked: 1
    - kind: theory2
      coef: 2.2
      hours: 40
      locked: 1
    - kind: thesis
      coef: 2.2
      hours: 64
      locked: 1
    - kind: thesis_reading
      hours: 48
      locked: 1

- name: Alain Bellet
  role: Professor
  percent: 50
  tasks:
    - kind: course
      course: 2cvmid12a
    - kind: course
      course: 2cvmid12c
    - kind: course
      course: 2cvmid22a
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc

- name: Angelo Benedetto
  role: Professor
  percent: 16
  tasks:
    - kind: course
      course: 1cvmid12a
    - kind: course
      course: 1cvmid12b
    - kind: course
      course: 1cvmid22a
    - kind: eval

- name: Gael Hugo
  role: Professor
  percent: 40
  tasks:
    - kind: course
      course: 1cvmid21a
    - kind: course
      course: 1cvmid22c
    - kind: course
      course: 2cvmid11a
    - kind: course
      course: 2cvmid21a
    - kind: course
      course: 3cvmid12
    - kind: course
      course: 3cvmid2
    - kind: eval
    - kind: diplome_blanc
    - kind: representation

- name: Cyril Diagne
  role: Professor
  percent: 60
  tasks:
    - kind: course
      course: 1cvmid11a
    - kind: course
      course: 1cvmid12b
    - kind: course
      course: 2cvmid12c
    - kind: course
      course: 3cvmid11
    - kind: course
      course: 3cvmid2
    - kind: entry_test
      hours: 24
    - kind: resp mid
      hours: 374
    - kind: projects
      hours: 80
    - kind: eval
    - kind: diplome_blanc

# Assistants

- name: Tibor Udvari
  role: Assistant
  percent: 40
  tasks:
  - kind: assist

- name: Laura Perrenoud
  role: Assistant
  percent: 30
  tasks:
  - kind: assist

- name: Marc Dubois
  role: Assistant
  percent: 30
  tasks:
  - kind: assist

- name: Romain Cazier
  role: Assistant
  percent: 30
  tasks:
  - kind: assist

# Lecturers

- name: Cedric Duchene
  role: Lecturer
  hours: 40
  tasks:
    - kind: course
      course: 2cvmid22b
    - kind: course
      course: 3cvmid2
- name: Andreas Gysin
  role: Lecturer
  hours: 80
  tasks:
    - kind: course
      course: 2cvmid11b
    - kind: course
      course: 1cvmid22c
- name: Mario VonRickenbach
  role: Lecturer
  hours: 136
  tasks:
    - kind: course
      course: 2cvmid12b
    - kind: course
      course: 1cvmid11c
    - kind: course
      course: 1cvmid21b
    - kind: course
      course: 3cvmid2
    - kind: eval
- name: Florian Pittet
  role: Lecturer
  hours: 40
  tasks:
    - kind: course
      course: 1cvmid12c
- name: Jussi Angesleva
  role: Lecturer
  hours: 24
  tasks:
    - kind: course
      course: 3cvmid11
