Staffs:

# Profs

- name: Patrick Keller
  role: Professor
  percent: 50
  tasks:
  - kind: course
    course: 1cvmid11b
  - kind: course
    course: 1cvmid21b
  - kind: theory1
    coef: 2.2
    hours: 40
  - kind: theory2
    coef: 2.2
    hours: 40
  - kind: r&d
    hours: 560

- name: Christophe Guignard
  role: Professor
  percent: 40
  tasks:
  - kind: course
    course: 3cvmid11
  - kind: course
    course: 3cvmid2
  - kind: pp
    coef: 2.2
    hours: 24
  - kind: theory1
    coef: 2.2
    hours: 40
  - kind: theory2
    coef: 2.2
    hours: 40
  - kind: thesis
    coef: 2.2
    hours: 64
  - kind: project_management
    coef: 2.2
    hours: 8

- name: Alain Bellet
  role: Professor
  percent: 50
  tasks:
  - kind: course
    course: 2cvmid12a
  - kind: course
    course: 2cvmid12c
  - kind: course
    course: 2cvmid22a
  - kind: course
    course: 3cvmid11
  - kind: course
    course: 3cvmid2

- name: Angelo Benedetto
  role: Professor
  percent: 16
  tasks:
  - kind: course
    course: 1cvmid12a
  - kind: course
    course: 1cvmid12b
  - kind: course
    course: 2cvmid22a

- name: Gael Hugo
  role: Professor
  percent: 40
  tasks:
  - kind: course
    course: 1cvmid21a
  - kind: course
    course: 1cvmid22c
  - kind: course
    course: 2cvmid11a
  - kind: course
    course: 2cvmid21a
  - kind: course
    course: 3cvmid12
  - kind: course
    course: 3cvmid2

- name: Cyril Diagne
  role: Professor
  percent: 60
  tasks:
  - kind: course
    course: 1cvmid11a
  - kind: course
    course: 1cvmid12b
  - kind: course
    course: 2cvmid12c
  - kind: course
    course: 3cvmid11
  - kind: course
    course: 3cvmid2
  - kind: entry_test
    hours: 24
  - kind: resp
    hours: 374
  - kind: projects
    hours: 80

# Assistants

- name: Tibor Udvari
  role: Assistant
  percent: 40

- name: Laura Perrenoud
  role: Assistant
  percent: 30

- name: Marc Dubois
  role: Assistant
  percent: 30

- name: Romain Cazier
  role: Assistant
  percent: 30
